=== ryseok/Java/0627/my_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>



<schema xmlns="http://www.w3.org/2001/XMLSchema" 
      targetNamespace="http://www.example.org/my_schema" 
      xmlns:tns="http://www.example.org/my_schema" 
      elementFormDefault="qualified">

  <element name="root">
     <complexType>
        <sequence>
            <element ref="tns:str" 
                     minOccurs="1"
                     maxOccurs="5"/> 
            <element ref="tns:su" />
            <element name="jumin" 
                     type="tns:juminType"/>
            <element name="cupSize"
                     type="tns:cupType"
                     minOccurs="1"
                     maxOccurs="unbounded"/>                     
        </sequence>
     </complexType>     
  </element>
  
  <element name="str" type="string"></element>
  <!-- str태그내에  문자열데이터 입력 -->
  
  <element name="su" type="int"></element>
  <!-- su태그내에  정수데이터 입력 -->
  
  <!-- 사용자 정의 자료형(패턴,list) -->
  <simpleType name="juminType">
     <restriction base="string">
       <pattern value="\d{6}-\d{7}"></pattern>
     </restriction>
  </simpleType>

  <!-- 컵사이즈에 대한 수치정의(10~50) -->
  <simpleType name="cup1">
    <restriction base="positiveInteger">
        <minInclusive value="10"/>
        <maxInclusive value="50"/>
    </restriction>
  </simpleType>
  
  <!-- 컵사이즈에 대한 문자정의 -->
  <simpleType name="cup2">
    <restriction base="string">
       <enumeration value="small"/>
       <enumeration value="medium"/>
       <enumeration value="large"/>
    </restriction> 
  </simpleType>
  
  <simpleType name="cupType">
     <union memberTypes="tns:cup1 tns:cup2"/>
  </simpleType>

</schema>

=== ryseok/Java/0627/my.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="http://www.example.org/my_schema" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.example.org/my_schema my_schema.xsd ">
  <str>str</str>
  <str>str</str> 
  <str>str</str> 
  <str>str</str> 
  <str>str</str>
  <su>0</su> 
  <jumin>960323-2012345</jumin>
  <cupSize>10</cupSize>
  <cupSize>50</cupSize>
  <cupSize>small</cupSize>
  <cupSize>large</cupSize>
</root>
